FROM public.ecr.aws/lambda/python:3.11
ENV PYTHONUNBUFFERED=1

WORKDIR /var/task

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY settings.py lambda_handler.py alembic.ini ./ 
COPY src ./src
COPY alembic ./alembic
COPY app.env . 

CMD ["lambda_handler.handler"]
