FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY settings.py main.py alembic.ini ./ 
COPY src ./src
COPY alembic ./alembic
COPY app.env .

CMD ["uvicorn", "main:server", "--host", "0.0.0.0", "--port", "8080"]
