"""Adding Media and MediaPermission Table

Revision ID: 64db2e655cdb
Revises: 0ec35163ed26
Create Date: 2024-04-26 18:49:17.421224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "64db2e655cdb"
down_revision: Union[str, None] = "0ec35163ed26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("media_owner", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("media_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=False),
        sa.Column("size_in_mb", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_owner"],
            ["user.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mediapermission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column(
            "granted_to_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "permission_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_to_username"],
            ["user.username"],
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mediapermission")
    op.drop_table("media")
    # ### end Alembic commands ###
