name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main  # Set to the branch you want to deploy from

jobs:
  deploy:
    name: Build, Tag, and Push Docker image to Amazon ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.TAG }} .

    - name: Tag Docker image
      run: docker tag ${{ secrets.IMAGE_NAME }}:${{ secrets.TAG }} ${{ secrets.ECR_REPOSITORY_URI }}:${{ secrets.TAG }}

    - name: Push Docker image to Amazon ECR
      run: docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ secrets.TAG }}
