name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
env:  # Define environment variables for the entire workflow
  ENVIRONMENT: "TESTING"

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Python 3.11.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Corrected to specify the file name

    - name: Create Test Database
      run: |
        PGPASSWORD=testpass psql -h localhost -U testuser -p 5433 -d postgres -c "CREATE DATABASE testdb OWNER testuser;"

    - name: Run migrations
      run: alembic upgrade head

    - name: Test
      run: make test
